language: ruby
rvm:
  - ruby-head
  - 2.1.0
  - 2.0.0
  - 1.9.3
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c678e69e182b141aa162
    on_success: always
    on_failure: always
    on_start: true
